### ISSUE TITLE
Unable to download the data from the link provided in the README.

### ISSUE THREAD

**Issue by WangYCheng23** [microsoft/VRL3#1]
Hi,

I'm looking to download the data from the link you provided: https://drive.google.com/drive/folders/14rH_QyigJLDWsacQsrSNV7b0PjXOGWwD?usp=sharing.

However, it seems that the link is outdated and the file is not accessible.

Could someone please share an updated link?

Thank you!

**Comment by watchernyu** [comment]
Hi! Sorry about the issue, we have just updated the link, can you try this one to see if it works? Thank you! 

https://drive.google.com/drive/folders/1j-7BKlYmknVCBfzO3MnLLD62JBngoMkn?usp=sharing

**Comment by WangYCheng23** [comment]
now it works! Thank you.
